### PR TITLE
Hlp 496

### LINKED ISSUE #496: Create "Time Start" component
Use data from Time Start and Time End selectors to populate slider for user to view changes

Reference roadmap in #443

### PR DESCRIPTION
**Pull request by hpodzorski-USGS**
# Pull Request Code Review

## Overview

Added a drop down to select a data set and creates a time slider.

## Links

- *Issues*: Closes #496 

## Summary of Changes

- Added code to `3_CONUS404_DRB_Visualization`

## Peer Reviewer Expectations

- [ ]  Review for correctness

### CODE REVIEW

**Review by alaws-USGS — CHANGES_REQUESTED** [review]
Before we merge this, lets add a base Panel app to start adding widgets to.

**Comment by hpodzorski-USGS** [comment]
I wasn't sure what you meant by panel base app, so let me know if my updates are sufficient.

**Comment by alaws-USGS** [comment]
I'll start my review

**Comment by alaws-USGS** [comment]
Hannah, check out the changes I made in branch https://github.com/hytest-org/hytest/tree/ARL-HLP-496. One thing that you want to do is use pn.bind() or pn.rx() to bind the inputs from widgets with functions to return what you want.

Also, we want the data_vars, not the long name, for our variable names.

**Comment by alaws-USGS** [comment]
@hpodzorski-USGS has this work been superceded by work on another branch? If so, can we close this pull request and have these changes be merged in elsewhere?

**Comment by hpodzorski-USGS** [comment]
> @hpodzorski-USGS has this work been superceded by work on another branch? If so, can we close this pull request and have these changes be merged in elsewhere?

Yes, it has been superseded by work in this issue [https://github.com/hytest-org/hytest/issues/518](https://github.com/hytest-org/hytest/issues/518). I will close this PR and merge the changes in the new issue.

**Pull request closed without merging**
