### PR TITLE
Nested intake catalogs

### PR DESCRIPTION
**Pull request by alaws-USGS**
I created an `intake` catalog for the CONUS404 DRB tutorials. I then added this as a nested catalog to HyTEST's primary `intake` catalog and put together a short notebook on how to access nested catalogs and its datasets.

### CODE REVIEW

**Comment by amsnyder** [comment]
Cool - thanks @alaws-USGS this was really helpful. Are these datasets that are read into the tutorial workflows from the intake catalog? Or are they outputs that you just gathered into a catalog to demonstrate this concept?

Trying to decide if we want to actually include this sub-catalog for people to reference and how it fits in with the bigger picture - so I'd like to understand where this data is currently used, and if you see other use cases for the data popping up in the future.

**Comment by alaws-USGS** [comment]
@amsnyder, these datasets will be read into my tutorials so the subcatalog will need to be kept.

**Comment by amsnyder** [comment]
Ok! I have a few suggested changes, but I'm open to pushback if any of them don't align with your views:
1. rename the entry to `conus404-drb-eval-tutorial-catalog`: to make it super clear that (1) this entry is a catalog and (2) it is for a specific eval tutorial (not just conus404 DRB data) - i know it's kinda lengthy but I err on the side of overly descriptive
2. move the sub-catalog yml into `dataset_catalog/subcatalogs` just to keep all of our data catalogs together (and update your notebook fp)
3. move the demo notebook into `dataset_catalog/demos` as it is a demonstration of how to use these catalogs
4. Update the end of the README.md with two pieces of info: (1) explain that we will create sub-catalogs for a variety of use cases that will be contained withing the subcatalogs folder, and (2) make a note that there are demonstrations of how to use the catalogs/subcatalogs in the `demos` folder

Let me know if you disagree with any of these!

**Comment by alaws-USGS** [comment]
@amsnyder I'll give these consideration and then provide feedback around the middle of next week.

**Comment by rsignell-usgs** [comment]
Sounds reasonable to me!

**Review by amsnyder — APPROVED** [review]

**Pull request merged**
