### PR TITLE
Update conus404-catalog.yml

### PR DESCRIPTION
**Pull request by alaws-USGS**

### CODE REVIEW

**Comment by alaws-USGS** [comment]
@amsnyder I'm getting an error when trying to use the CONUS404 hourly OSN dataset. In our YAML it says consilidated is true but the error is due to the metadata on OSN potentially not being consilidated. I wanna see if this is the issue.

**Review by kjdoore — APPROVED** [review]
Looks like that should do the trick.

**Comment by amsnyder** [comment]
@pnorton-usgs - is this expected for the CONUS404 hourly data to have unconcolidated metadata? could this be an inssue with the update to the variables in the consolidated metadata file?

**Comment by amsnyder** [comment]
@pnorton-usgs - sorry, disregard. I see this got changed back in #416 - I am playing catch up

**Pull request merged**
