### PR TITLE
Update notebook prior to Hannah's work

### PR DESCRIPTION
**Pull request by alaws-USGS**
Updates to CONUS404 forcings evaluation notebook 1

### CODE REVIEW

**Comment by sfoks** [comment]
Doing some super quick running of notebook 1 on Nebari using pangeo-dev kernel, its super quick. Just ran into index error on this cellblock in Step 3.
image

And an error when trying to read in PRISM but probably because I don't have my credentials setup. I will check the rest of this on Thurs.

**Comment by alaws-USGS** [comment]
@sfoks did you draw anything in the map above? Otherwise, you will then get that IndexError if you didn't. Otherwise, I may need to rework it.

**Comment by sfoks** [comment]
This is great so far.

I have a minor edits to markdown language:
- 1st markdown cell: remove the "(to add: tmin, tmax, radiation components)" from the bullet point labeled 'Variables'.
- 2nd markdown cell: Replace QHUB w/ something more generic like "cloud-based jupyterhub (i.e., ESIP-Nebari)."
- 4th MD cell: We may want to just link to the hytest repo/jupyter book that [explains the data types/locs ](https://hytest-org.github.io/hytest/dataset_catalog/README.html) so we don't have to update this explanation in the future, and then just explain something along the lines of "for explanation of data naming and storage locations, please see [link]. You will want to use data for where you are working (i.e., if you are working on a cloud-based jupyterhub, you will want to use data stored on the cloud)."
- 5th MD cell: I think this may need some instructions for a user. I would adjust the title to be more generic so "You can setup your client and dataset for the compute environment you are working on" - then I would add some language about "adjusting the dataset name below to correspond to the dataset of interest you are working on. For this tutorial, we are focusing on the CONUS404 hourly dataset".
- 7th MD cell: We should remove the Hytest Sharepoint link since its internal to USGS only and cite the [CONUS404 variable descriptions](https://rda.ucar.edu/datasets/ds559.0/documentation/#) from NCAR.

Some questions about code cells:
- I wasn't able to access PRISM V2 in ESIP-Nebari. I was thrown a Forbidden error, potentially PRISM V2 needs AWS permissions? If so, we will want to mention that in the markdown cell above or consider putting PRISM V2 on OSN for tutorials and for hytest Eval team if we are running into this issue.
- In the points reference data section, trying to clip the points to DRB, I am getting "IndexError: list index out of range" on 
image

**Comment by alaws-USGS** [comment]
@sfoks, I addressed each of the minor edits you asked for.

For the dataset, I will talk with Amelia about the OSN pod/look at other methods of bringing in the data.

**Review by sfoks — APPROVED** [review]

**Pull request merged**
